### ISSUE TITLE
Can prim.js be used as a promise-shim for non-alameda apps?

### ISSUE THREAD

**Issue by xwisdom** [requirejs/alameda-prim#1]
Hello James,

Just want to get your feeback on prim.js

Can prim.js be used as a promise-shim for non-alameda apps? Is it Promise/A+ compatible?

Best regards,
__
Raymond

**Comment by jrburke** [comment]
It passes the 2.1.1 version of the Promises/A+ tests (the last released version of the tests, done in July of last year, so it should be generically useful, but see the README in the [prim repo](https://github.com/requirejs/prim) for full information. I am not likely to do bug fixes around it that try to get it to conform to specific native promise implementations though, I prefer just using the Promises/A+ tests as the measure for it. I also expect updates to prim be slow if future Promises/A+ tests are released.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by xwisdom** [comment]
I'm looking for a lightweight promise shim library that's compatible with the Promise/A+ spec. If prim can pass the tests then it should work just fine.
